# This is a basic workflow to help you get started with Actions

name: CI-local

on: [push]

jobs:
  hello_world_job:
    name: Common PR job
    uses: jglynn/reusable-workflows/blob/main/.github/workflows/common-pr.yml@main
        
