# This is a basic workflow to help you get started with Actions

name: CI-local

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: simple-composite-action
        uses: jglynn/simple-composite-action@main
