#
# Invoke a reusbale workflow with a callback workflow as input
# 
name: pr-workflow

on: [push]

jobs:
  pr-workflow-job:
    name: Common PR job
    uses: jglynn/reusable-workflows/.github/workflows/common-pr.yml@main
    with: 
      workflow_ref: jglynn/simple-composite-action/.github/workflows/ci.yml@main
        
