# This is a basic workflow to help you get started with Actions

name: pr-workflow

on: [push]

jobs:
  pr-workflow-job:
    name: Common PR job
    uses: jglynn/reusable-workflows/.github/workflows/common-pr.yml@main
    with: 
      workflow_ref: jglynn/simple-composite-action/.github/workflows/ci.yml
        
